add user personas
irene2mana-T3A2-2023/online-japanese-grocery-store pull request #4
Opened 2023-11-19 11:39 UTC by Mana12011207

Please review user personas and descriptions.

2023-11-19 11:53 UTC, irenenguyen1017 approved these changes

2023-11-19 12:04 UTC, ellenpham commented on README.md
> +A problem Shizuka faces is the difficulty travelling to supermarkets where authentic Japanese food products are available, even with her three children. With the demands of raisingtrello  her childre
This sentence is not very concise, maybe changed from..

`A problem Shizuka faces is the difficulty travelling to supermarkets where authentic Japanese food products are available, even with her three children. With the demands of raisingtrello  her children, she also needs to save time when shopping for her daily food.`

to

"Shizuka, a mom of three, is facing the difficulty of travelling to supermarkets in a daily basis to shop for authentic Japanese food products. She needs a online grocery website that is user-friendly and easy navigated where she can browse and shop online when the kids are taking a nap and get the products delivered to home without the hassle of going to the physical shops."


Also, maybe change this term `secure login facility` to "secure login feature"

2023-11-19 12:10 UTC, ellenpham commented on README.md
> +On the other hand, Ronnie, a user who has recently become addicted to Japanese food, also faces difficulties in finding Japanese foodstuffs locally. Ronnie is also an engineer. The engineer, Ronnie,
This sentence, you can add some more info:

`On the other hand, Ronnie, a user who has recently become addicted to Japanese food, also faces difficulties in finding Japanese foodstuffs locally`

--> "On the other hand, Ronnie, a user who has recently become addicted to Japanese food, also faces the difficulty of finding unique and authentic Japanese food products locally. He also prefer a clear product description written in English as he has a hard time choosing the right product when the product labels are mostly written in Japanese."

2023-11-19 12:11 UTC, ellenpham commented on README.md
> +The final user story focuses on Lara, a system administrator at Sakura Company. She aims to ensure efficient operations and deliver the best user experience. High-quality user and product inventory m
maybe change `High-quality user` to `A reliable user database`

2023-11-19 12:13 UTC, ellenpham commented on README.md
> +We construct user stories and personas to improve the online store's user experience for Japanese food products. The process involves identifying and embodying potential users' unique needs and expec
Just a few minor spelling and formatting mistakes here and there. I suggest paste the paragraph to Word and spell check first before pasting back to Markdown.

2023-11-19 12:14 UTC, ellenpham commented on docs/images/user-pesonas/Sizuka-kagami.png
I think the preferred features is missing? `Secure logout for????`

2023-11-19 22:52 UTC, Mana12011207 commented
Please review user stories again.

2023-11-20 00:40 UTC, irenenguyen1017 commented
I'm ready to approve your PR. However, I noticed that Ellen has some comments, and I'm not sure if they've been included in your latest version. Please discuss these with Ellen to ensure everything is addressed before merging your PR.

2023-11-20 00:51 UTC, ellenpham commented on docs/images/user-pesonas/Shizuka-Kagami.png
There's still a missing bit of "Preferred feature", `Secure logout for ???`

2023-11-20 00:52 UTC, ellenpham requested changes
I think there're still missing details in the persona of Shizuka, please check out comment.

2023-11-20 11:01 UTC, ellenpham commented on docs/images/user-pesonas/Shizuka-Kagami.png
Hi Mana, I noticed that this still has not been fixed, can you please check again so we can tick off this task?

2023-11-22 00:10 UTC, ellenpham requested changes
Hi Mana, sorry for the back and forth changes but I realized again that the preferred features in the user stories need to be aligned with our features and vice versa. Hopefully this is the last changes.

I comment here so you dont have to go back for the comment in Discord chat history

I think a little changes need to be made for Ronnie and Shizuka user stories:

**Ronnie's motivations:** 

- New discoveries
- Wide range of choices 

(no need delivery because we dont do that feature)

**Ronnie's preferred features:**

- Intuitive platform...
- Simple and effortless...
- **New arrivals section for suggestion of new products** 
- **Search products by name for easily finding particular favorite product**

**Shizukar's preffered features:**
- Secure..
- Saved login...
- Convenient...
- **Order confirmation via email to easily track order as she tends to be forgetful sometimes.** 

Afterwards, you can add Jinny's user story with the below description on top:

"Not everyone know about the website before stumbling on it while browsing the internet, Jinny is one of those people. She is among numerous random shoppers, who are the potential users of the website. As a first-time user, she expects the design and layout of the website to be appealing and memorable, easy and clear navigation to make her first shopping experience effortless and seamless. This would make her come back to shop the next time. Also, she would love to know the popular products with description in English and recommended list of products that go together to gather ideas for her cooking recipes. "

2023-11-28 04:44 UTC, irenenguyen1017 requested changes

2023-11-28 04:44 UTC, irenenguyen1017 commented on README.md
> +
This feature has been moved to the 'nice-to-have' list. Currently, we are only providing users with the ability to change their password.

2023-11-28 04:44 UTC, irenenguyen1017 commented on README.md
> +
This implies that users are required to input their delivery address each time they make a purchase.

2023-11-28 04:44 UTC, irenenguyen1017 commented on docs/images/user-pesonas/Jinny_Chang.png
Just a heads-up, it's not a big deal, but have you noticed that Jinny's salary is getting pretty close to Lara's, and she's in admin?

2023-11-28 04:44 UTC, irenenguyen1017 commented on README.md
> +8. As an administrator, I want the ability to efficiently manage users by viewing their information and assisting with account-related matters.
I think we won't go far in assisting with account-related issues, so could you please change this to something like  'As an administrator, I want to capture store analytics data to inform our development strategy, so I can ensure our resources are effectively aligned with business growth.'

2023-11-28 04:47 UTC, ellenpham requested changes

2023-11-28 04:47 UTC, ellenpham commented on README.md
> +8. As an administrator, I want the ability to efficiently manage users by viewing their information and assisting with account-related matters.
We only keep Read operation for admin, so other operations on users including Update and Deactivate, might have to move to nice-to-have.

2023-11-28 04:47 UTC, ellenpham commented on README.md
> +
Can you add more user stories for the below features:

- Password recovery
- Site navigation and responsive design
- Shopping cart: allow users to add products to cart, view items in cart and increase, decrease or remove items from cart.
- User functionality to view order history

2023-11-28 04:47 UTC, ellenpham commented on README.md
> +3. As a user who often changes residence, I need to easily update my profile to ensure accurate delivery despite frequent changes in residence.
This one moves to nice-to-have as we dont have edit user profile for MVP features anymore

2023-11-28 04:47 UTC, ellenpham commented on README.md
> +4. As a user, I want the convenience of a Product Search Bar that allows me to find specific pantry items effortlessly. This will save me time and ensure that I quickly locate the products I'm lookin
Maybe change `I want the convenience of a Product Search Bar`

to `I want to be able to search products by keywords, which allows me to ......`

2023-11-28 04:47 UTC, ellenpham commented on README.md
> +9. As an administrator, the ability to perform CRUD operations on products and select quantities will enable me to manage product inventory efficiently and maintain accurate stock listings.
Can you add CRUD operations for product categories as well?

I'm nore sure what do you mean by "select quantities"?

2023-11-28 04:47 UTC, ellenpham commented on README.md
> +
Can you add one more user story about the Data Summary for admin dashboard, a summary view of total users, total products, total orders and total revenue?

2023-11-28 04:47 UTC, ellenpham commented on README.md
> +
I think this part is missing quite a few nice-to-have features. Can you refer to the project description to add some more?

2023-11-28 11:23 UTC, ellenpham approved these changes

2023-11-28 11:52 UTC, irenenguyen1017 approved these changes

2023-11-28 23:20 UTC, merged